Adapt folder layout and finish pandoc integration (#69)
Completes the necessary folder layout rework and refactors pandoc file generation to work together with the rest of the tooling/setup. This finally finishes the pandoc integration to automatically generate teaching docs.

diff --git a/tools/build/aspell_frontend b/tools/build/aspell_frontend
--- a/tools/build/aspell_frontend
+++ b/tools/build/aspell_frontend
@@ -1,16 +1,14 @@
 #! /usr/bin/env bash
-# Michael Adams (mdadams@ece.uvic.ca)
 
 cmd_dir="$(dirname "$0")" || exit 1
-
-# Get an absolute pathname.
-#cmd_dir=$(realpath "$cmd_dir") || exit 1
 
 top_dir="$cmd_dir/../.."
 spellcheck_dir="$top_dir/config/spellcheck"
 wordlist="wordlist"
 if [ ! -f "$spellcheck_dir/$wordlist" ]; then
-	echo "ERROR"
-	exit 1
+  echo "ERROR"
+  exit 1
 fi
-exec aspell --home-dir="$spellcheck_dir" --personal "$wordlist" "$@"
+tmp_wordlist=$(mktemp /tmp/wordlist.XXXXXX)
+cat $spellcheck_dir/wordlist $spellcheck_dir/ignored_words.txt > $tmp_wordlist
+exec aspell --home-dir="$spellcheck_dir" --personal $tmp_wordlist --lang en "$@"
diff --git a/tools/build/build b/tools/build/build
--- a/tools/build/build
+++ b/tools/build/build
@@ -7,38 +7,37 @@
 # Terminate with error.
 panic()
 {
-	echo "ERROR: $@" 1>&2
-	exit 1
+  echo "ERROR: $@" 1>&2
+  exit 1
 }
 
 # Print usage information.
 usage()
 {
-	echo "bad usage: $@"
-	cat <<- EOF
-	build - Build the document.
+  echo "bad usage: $@"
+  cat <<  EOF
+  build - Build the document.
 
-	Usage
-	=====
+  Usage
+  =====
 
-	$0 -d \$install_dir -z \$github_ref
+  $0 -d \$install_dir -v \$version
 
-	Options
-	=======
+  Options
+  =======
 
-	-d \$install_dir
-	Set the installation directory for the built release to \$install_dir.
+  -d \$install_dir
+  Set the installation directory for the built release to \$install_dir.
 
-	-z \$github_ref
-	Set the GitHub ref to $\github_ref.
-	(This is used to determine the version of the document being released.)
+  -v \$version
+  Set the document version $\version.
 
-	Examples
-	========
+  Examples
+  ========
 
-	$0 -d /tmp/sg20_test/install -z refs/tags/v0.0.1
-	EOF
-	exit 2
+  $0 -d /tmp/sg20_test/install -v v0.0.1
+EOF
+  exit 2
 }
 
 ################################################################################
@@ -53,41 +52,38 @@ source_dir="$cmd_dir/../.."
 ################################################################################
 
 install_dir=
-github_ref=
+version=
 spellcheck=0
 
-while getopts d:z:s opt; do
-	case $opt in
-	d)
-		install_dir="$OPTARG";;
-	z)
-		github_ref="$OPTARG";;
-	s)
-		spellcheck=1;;
-	\?)
-		usage
-		break;;
-	esac
+while getopts d:v:s opt; do
+  case $opt in
+  d)
+    install_dir="$OPTARG";;
+  v)
+    version="$OPTARG";;
+  s)
+    spellcheck=1;;
+  \?)
+    usage
+    break;;
+  esac
 done
 shift $((OPTIND - 1))
 
 if [ -z "$install_dir" ]; then
-	usage "no output directory specified"
+  usage "no output directory specified"
 fi
-if [ -z "$github_ref" ]; then
-	usage "no github ref specified"
+if [ -z "$version" ]; then
+  usage "no document version specified"
 fi
 
 ################################################################################
 # Build the document.
 ################################################################################
 
-version="$(awk -v FS="/" '{print $3;}' <<< "$github_ref")" || \
-  panic "cannot determine document version"
-
 if [ ! -d "$install_dir" ]; then
-	mkdir -p "$install_dir" || \
-	  panic "cannot make installation directory $install_dir"
+  mkdir -p "$install_dir" || \
+    panic "cannot make installation directory $install_dir"
 fi
 
 (cd "$source_dir" && make clean) || \
@@ -97,5 +93,12 @@ fi
   make DOC_VERSION="$version" DOC_SPELLCHECK_MUST_PASS="$spellcheck" all) || \
   panic "cannot build document"
 
-make INSTALL_DIR="$install_dir" install || \
+make DOC_VERSION="$version" INSTALL_DIR="$install_dir/$version" install || \
   panic "cannot install release"
+
+cp $source_dir/sources/index.html $install_dir
+
+pushd $install_dir
+unlink latest
+ln -s $version/html latest
+popd
