Added a logo to the document title and made a few other minor changes to the document. Performed some clean up on the makefile and added a few comments to it as well. Added some comments and better error messages to the document build script. Made numerous improvements to the document deploy script (e.g., added usage information and added a few comments). Added some comments to the GitHub workflow files.

diff --git a/build/build b/build/build
--- a/build/build
+++ b/build/build
@@ -1,23 +1,51 @@
 #! /usr/bin/env bash
-# Michael Adams (mdadams@ece.uvic.ca)
 
-cmd_dir=$(dirname "$0") || exit 1
-source_dir="$cmd_dir/.."
+################################################################################
+# Some helper functions.
+################################################################################
 
+# Terminate with error.
 panic()
 {
-	echo "ERROR: $@"
+	echo "ERROR: $@" 1>&2
 	exit 1
 }
 
+# Print usage information.
 usage()
 {
 	echo "bad usage: $@"
 	cat <<- EOF
-	$0 -d install_dir -z github_ref
+	build - Build the document.
+
+	Usage
+	=====
+
+	$0 -d \$install_dir -z \$github_ref
+
+	Options
+	=======
+
+	-d \$install_dir
+	Set the installation directory for the built release to \$install_dir.
+
+	-z \$github_ref
+	Set the GitHub ref to $\github_ref.
+	(This is used to determine the version of the document being released.)
 	EOF
 	exit 2
 }
+
+################################################################################
+# Perform some basic initialization.
+################################################################################
+
+cmd_dir=$(dirname "$0") || panic "cannot determine directory name"
+source_dir="$cmd_dir/.."
+
+################################################################################
+# Parse command line.
+################################################################################
 
 install_dir=
 github_ref=
@@ -45,18 +73,24 @@ if [ -z "$github_ref" ]; then
 	usage "no github ref specified"
 fi
 
-version="$(awk -v FS="/" '{print $3;}' <<< "$github_ref")" || panic
+################################################################################
+# Build the document.
+################################################################################
+
+version="$(awk -v FS="/" '{print $3;}' <<< "$github_ref")" || \
+  panic "cannot determine document version"
 
 if [ ! -d "$install_dir" ]; then
-	mkdir -p "$install_dir" || panic
+	mkdir -p "$install_dir" || \
+	  panic "cannot make installation directory $install_dir"
 fi
 
-(cd "$source_dir" && make clean) || panic
+(cd "$source_dir" && make clean) || \
+  panic "cannot make clean"
 
 (cd "$source_dir" && \
   make DOC_VERSION="$version" DOC_SPELLCHECK_MUST_PASS="$spellcheck" all) || \
-  panic
+  panic "cannot build document"
 
-INSTALL_DIR="$install_dir" make install
-#cp "$source_dir/guidelines.html" "$install_dir/index.html" || panic
-#cp "$source_dir/pandoc.css" "$install_dir" || panic
+INSTALL_DIR="$install_dir" make install || \
+  panic "cannot install release"
diff --git a/build/deploy b/build/deploy
--- a/build/deploy
+++ b/build/deploy
@@ -1,20 +1,52 @@
 #! /usr/bin/env bash
-# Michael Adams (mdadams@ece.uvic.ca)
 
-cmd_dir=$(dirname "$0") || exit 1
-source_dir="$cmd_dir/.."
+################################################################################
+# Some helper functions.
+################################################################################
 
+# Terminate with error.
 panic()
 {
-	echo "ERROR: $@"
+	echo "ERROR: $@" 1>&2
 	exit 1
 }
 
 usage()
 {
 	echo "bad usage: $@"
+	cat <<- EOF
+	deploy - deploy new release of document to GitHub Pages repository
+
+	Usage
+	=====
+
+	$0 [options]
+
+	Options
+	=======
+
+	-b \$branch
+	    Set the deployment branch to \$branch.
+	-t \$tmp_dir
+	    Set the temporary directory to $\tmp_dir.
+	-i \$in_dir
+	    Set the input directory to \$in_dir.
+	-r \$repo_name
+	    Set the deployment repository to \$repo_name.
+	-z \$github_ref
+	    Set the GitHub ref to \$github_ref.
+	-f
+	    Allow private key file to be overwritten.
+	-n
+	    Prepare to push to deployment repository but do not actually
+	    push the changes.  (This is only for testing purposes.)
+	EOF
 	exit 2
 }
+
+################################################################################
+# Parse command line.
+################################################################################
 
 branch="gh-pages"
 in_dir=
@@ -23,6 +55,7 @@ tmp_dir="${TMPDIR:-/tmp}"
 github_ref=
 force=0
 prepare_only=0
+verbose=1
 
 while getopts b:i:r:t:z:fn opt; do
 	case $opt in
@@ -68,7 +101,16 @@ echo "input directory $in_dir"
 echo "repository name $repo_name"
 echo "github ref $github_ref"
 
-version="$(awk -v FS="/" '{print $3;}' <<< "$github_ref")" || panic
+################################################################################
+# Perform some basic initialization.
+################################################################################
+
+cmd_dir=$(dirname "$0") || \
+  panic "cannot determine directory"
+source_dir="$cmd_dir/.."
+
+version="$(awk -v FS="/" '{print $3;}' <<< "$github_ref")" || \
+  panic "cannot determine document version"
 echo "version $version"
 
 tmp_dir="$tmp_dir/deploy"
@@ -76,16 +118,24 @@ tmp_dir="$tmp_dir/deploy"
 git_dir="$tmp_dir/git"
 ssh_dir="$HOME/.ssh"
 private_key_file="$ssh_dir/private_key"
+version_dir="$git_dir/$version"
+repo_url="ssh://git@github.com/$repo_name.git"
+
+################################################################################
+# Setup SSH client configuration.
+################################################################################
 
 if [ "$force" -eq 0 -a -e "$private_key_file" ]; then
 	panic "private key file already exists"
 fi
 
 if [ ! -d "$ssh_dir" ]; then
-	mkdir -p "$ssh_dir" || panic "cannot make directory $ssh_dir"
+	mkdir -p "$ssh_dir" || \
+	  panic "cannot make directory $ssh_dir"
 fi
 if [ ! -d "$tmp_dir" ]; then
-	mkdir -p "$ssh_dir" || panic "cannot make directory $ssh_dir"
+	mkdir -p "$ssh_dir" || \
+	  panic "cannot make directory $ssh_dir"
 fi
 
 echo "$DEPLOY_KEY" > "$private_key_file" || \
@@ -93,17 +143,22 @@ echo "$DEPLOY_KEY" > "$private_key_file" || \
 chmod u+rw,g=,o= "$private_key_file" || \
   panic "cannot set permissions for private key file"
 
-version_dir="$git_dir/$version"
-repo_url="ssh://git@github.com/$repo_name.git"
-
 if [ -z "$SSH_AGENT_PID" ]; then
-	eval $(ssh-agent) || panic "cannot start ssh-agent"
+	eval $(ssh-agent) || \
+	  panic "cannot start ssh-agent"
 fi
-ssh-add "$private_key_file" || panic "ssh-add failed"
+ssh-add "$private_key_file" || \
+  panic "ssh-add failed"
+
+################################################################################
+# Add new release to GitHub pages repository.
+################################################################################
 
 git clone "$repo_url" "$git_dir" || \
   panic "clone failed"
 
+# Create an orphaned branch for the web site content if the branch does
+# not already exist.
 git -C "$git_dir" ls-remote --exit-code --heads "$repo_url" "$branch" \
   > /dev/null
 status=$?
@@ -142,11 +197,13 @@ fi
 ln -s "latest/index.html" "$target" || \
   panic "ln failed"
 
-ls -al "$git_dir"/*
+if [ "$verbose" -ne 0 ]; then
+	ls -al "$git_dir"/*
+fi
 
 git -C "$git_dir" add . || \
   panic "git add failed"
-git -C "$git_dir" commit -m "Deploying" || \
+git -C "$git_dir" commit -m "Deploying release $version" || \
   panic "git commit failed"
 if [ "$prepare_only" -eq 0 ]; then
 	echo "Pushing changes."
diff --git a/build/prebuild b/build/prebuild
--- a/build/prebuild
+++ b/build/prebuild
@@ -1,10 +1,19 @@
 #! /usr/bin/env bash
-# Michael Adams (mdadams@ece.uvic.ca)
 
+# Terminate with error.
+panic()
+{
+	echo "ERROR: $@" 1>&2
+	exit 1
+}
+
+# Initialize the list of required packages.
 packages=()
 packages+=(pandoc)
 packages+=(texinfo)
 packages+=(aspell)
 #packages+=(hunspell)
 
-sudo apt-get install -y "${packages[@]}"
+# Install the packages.
+sudo apt-get install -y "${packages[@]}" || \
+  panic "unable to install packages"
